export const INCR = 'INCR';

export const GET_KEKS_PENDING = 'GET_KEKS';
export const GET_KEKS_FULFILLED = 'GET_KEKS_FULFILLED';
export const GET_KEKS_REJECTED = 'GET_KEKS_REJECTED';

export const STORE_KEK_PENDING = 'STORE_KEK';
export const STORE_KEK_FULFILLED = 'STORE_KEK_FULFILLED';
export const STORE_KEK_REJECTED = 'STORE_KEK_REJECTED';


// USERS
export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING';
export const REGISTER_USER_FULFILLED = 'REGISTER_USER_FULFILLED';
export const REGISTER_USER_REJECTED = 'REGISTER_USER_REJECTED';

export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';

export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_FULFILLED = 'GET_USERS_FULFILLED';
export const GET_USERS_REJECTED = 'GET_USERS_REJECTED';

export const GET_SINGLE_USER_PENDING = 'GET_SINGLE_USER_PENDING';
export const GET_SINGLE_USER_FULFILLED = 'GET_SINGLE_USER_FULFILLED';
export const GET_SINGLE_USER_REJECTED = 'GET_SINGLE_USER_REJECTED';


// ITEMS
export const GET_ITEMS_PENDING = 'GET_ITEMS_PENDING';
export const GET_ITEMS_FULFILLED = 'GET_ITEMS_FULFILLED';
export const GET_ITEMS_REJECTED = 'GET_ITEMS_REJECTED';

export const GET_SINGLE_ITEM_PENDING = 'GET_SINGLE_ITEM_PENDING';
export const GET_SINGLE_ITEM_FULFILLED = 'GET_SINGLE_ITEM_FULFILLED';
export const GET_SINGLE_ITEM_REJECTED = 'GET_SINGLE_ITEM_REJECTED';

export const CREATE_ITEM_PENDING = 'CREATE_ITEM_PENDING';
export const CREATE_ITEM_FULFILLED = 'CREATE_ITEM_FULFILLED';
export const CREATE_ITEM_REJECTED = 'CREATE_ITEM_REJECTED';

export const UPDATE_ITEM_PENDING = 'UPDATE_ITEM_PENDING';
export const UPDATE_ITEM_FULFILLED = 'UPDATE_ITEM_FULFILLED';
export const UPDATE_ITEM_REJECTED = 'UPDATE_ITEM_REJECTED';

export const DELETE_ITEM_PENDING = 'DELETE_ITEM_PENDING';
export const DELETE_ITEM_FULFILLED = 'DELETE_ITEM_FULFILLED';
export const DELETE_ITEM_REJECTED = 'DELETE_ITEM_REJECTED';

