// USERS
export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING';
export const REGISTER_USER_FULFILLED = 'REGISTER_USER_FULFILLED';
export const REGISTER_USER_REJECTED = 'REGISTER_USER_REJECTED';

export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';

export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_FULFILLED = 'GET_USERS_FULFILLED';
export const GET_USERS_REJECTED = 'GET_USERS_REJECTED';

export const GET_SINGLE_USER_PENDING = 'GET_SINGLE_USER_PENDING';
export const GET_SINGLE_USER_FULFILLED = 'GET_SINGLE_USER_FULFILLED';
export const GET_SINGLE_USER_REJECTED = 'GET_SINGLE_USER_REJECTED';

// ITEMS
export const GET_ITEMS_PENDING = 'GET_ITEMS_PENDING';
export const GET_ITEMS_FULFILLED = 'GET_ITEMS_FULFILLED';
export const GET_ITEMS_REJECTED = 'GET_ITEMS_REJECTED';

export const GET_SINGLE_ITEM_PENDING = 'GET_SINGLE_ITEM_PENDING';
export const GET_SINGLE_ITEM_FULFILLED = 'GET_SINGLE_ITEM_FULFILLED';
export const GET_SINGLE_ITEM_REJECTED = 'GET_SINGLE_ITEM_REJECTED';

export const CREATE_ITEM_PENDING = 'CREATE_ITEM_PENDING';
export const CREATE_ITEM_FULFILLED = 'CREATE_ITEM_FULFILLED';
export const CREATE_ITEM_REJECTED = 'CREATE_ITEM_REJECTED';

export const UPDATE_ITEM_PENDING = 'UPDATE_ITEM_PENDING';
export const UPDATE_ITEM_FULFILLED = 'UPDATE_ITEM_FULFILLED';
export const UPDATE_ITEM_REJECTED = 'UPDATE_ITEM_REJECTED';

export const DELETE_ITEM_PENDING = 'DELETE_ITEM_PENDING';
export const DELETE_ITEM_FULFILLED = 'DELETE_ITEM_FULFILLED';
export const DELETE_ITEM_REJECTED = 'DELETE_ITEM_REJECTED';

export const SEARCH_ITEM_PENDING = 'SEARCH_ITEM_PENDING';
export const SEARCH_ITEM_FULFILLED = 'SEARCH_ITEM_FULFILLED';
export const SEARCH_ITEM_REJECTED = 'SEARCH_ITEM_REJECTED';

// CART
export const ADD_ITEM_TO_CART_PENDING = 'ADD_ITEM_TO_CART_PENDING';
export const ADD_ITEM_TO_CART_FULFILLED = 'ADD_ITEM_TO_CART_FULFILLED';
export const ADD_ITEM_TO_CART_REJECTED = 'ADD_ITEM_TO_CART_REJECTED';

export const REMOVE_ITEM_FROM_CART_PENDING = 'REMOVE_ITEM_FROM_CART_PENDING';
export const REMOVE_ITEM_FROM_CART_FULFILLED = 'REMOVE_ITEM_FROM_CART_FULFILLED';
export const REMOVE_ITEM_FROM_CART_REJECTED = 'REMOVE_ITEM_FROM_CART_REJECTED';

export const REMOVE_ALL_ITEMS_FROM_CART_PENDING = 'REMOVE_ALL_ITEMS_FROM_CART_PENDING';
export const REMOVE_ALL_ITEMS_FROM_CART_FULFILLED = 'REMOVE_ALL_ITEMS_FROM_CART_FULFILLED';
export const REMOVE_ALL_ITEMS_FROM_CART_REJECTED = 'REMOVE_ALL_ITEMS_FROM_CART_REJECTED';

export const GET_CART_ITEMS_PENDING = 'GET_CART_ITEMS_PENDING';
export const GET_CART_ITEMS_FULFILLED = 'GET_CART_ITEMS_FULFILLED';
export const GET_CART_ITEMS_REJECTED = 'GET_CART_ITEMS_REJECTED';

// COMMENTS
export const GET_COMMENTS_PENDING = 'GET_COMMENTS_PENDING';
export const GET_COMMENTS_FULFILLED = 'GET_COMMENTS_FULFILLED';
export const GET_COMMENTS_REJECTED = 'GET_COMMENTS_REJECTED';

export const CREATE_COMMENT_PENDING = 'CREATE_COMMENT_PENDING';
export const CREATE_COMMENT_FULFILLED = 'CREATE_COMMENT_FULFILLED';
export const CREATE_COMMENT_REJECTED = 'CREATE_COMMENT_REJECTED';

export const UPDATE_COMMENT_PENDING = 'UPDATE_COMMENT_PENDING';
export const UPDATE_COMMENT_FULFILLED = 'UPDATE_COMMENT_FULFILLED';
export const UPDATE_COMMENT_REJECTED = 'UPDATE_COMMENT_REJECTED';

export const DELETE_COMMENT_PENDING = 'DELETE_COMMENT_PENDING';
export const DELETE_COMMENT_FULFILLED = 'DELETE_COMMENT_FULFILLED';
export const DELETE_COMMENT_REJECTED = 'DELETE_COMMENT_REJECTED';

export const CREATE_REPLY_PENDING = 'CREATE_REPLY_PENDING';
export const CREATE_REPLY_FULFILLED = 'CREATE_REPLY_FULFILLED';
export const CREATE_REPLY_REJECTED = 'CREATE_REPLY_REJECTED';

export const LIKE_COMMENT_PENDING = 'LIKE_COMMENT_PENDING';
export const LIKE_COMMENT_FULFILLED = 'LIKE_COMMENT_FULFILLED';
export const LIKE_COMMENT_REJECTED = 'LIKE_COMMENT_REJECTED';

export const DISLIKE_COMMENT_PENDING = 'DISLIKE_COMMENT_PENDING';
export const DISLIKE_COMMENT_FULFILLED = 'DISLIKE_COMMENT_FULFILLED';
export const DISLIKE_COMMENT_REJECTED = 'DISLIKE_COMMENT_REJECTED';

// ORDER
export const SUBMIT_ORDER_PENDING = 'SUBMIT_ORDER_PENDING';
export const SUBMIT_ORDER_FULFILLED = 'SUBMIT_ORDER_FULFILLED';
export const SUBMIT_ORDER_REJECTED = 'SUBMIT_ORDER_REJECTED';

export const GET_TRANSLATIONS_PENDING = 'GET_TRANSLATIONS_PENDING';
export const GET_TRANSLATIONS_FULFILLED = 'GET_TRANSLATIONS_FULFILLED';
export const GET_TRANSLATIONS_REJECTED = 'GET_TRANSLATIONS_REJECTED';

// VIEWED PRODUCTS

export const TOGGLE_PRODUCT_LIKE_PENDING = 'TOGGLE_PRODUCT_LIKE_PENDING';
export const TOGGLE_PRODUCT_LIKE_FULFILLED = 'TOGGLE_PRODUCT_LIKE_FULFILLED';
export const TOGGLE_PRODUCT_LIKE_REJECTED = 'TOGGLE_PRODUCT_LIKE_REJECTED';

export const DELETE_VIEWED_PRODUCT_PENDING = 'DELETE_VIEWED_PRODUCT_PENDING';
export const DELETE_VIEWED_PRODUCT_FULFILLED = 'DELETE_VIEWED_PRODUCT_FULFILLED';
export const DELETE_VIEWED_PRODUCT_REJECTED = 'DELETE_VIEWED_PRODUCT_REJECTED';

// USER ORDERS

export const TOGGLE_SELECT = 'TOGGLE_SELECT';